# LOG函数需要的常量
WITH_LINE_FEED = 1
WITHOUT_LINE_FEED = 0
# 验证码函数需要的常量
LOGIN_SUCCESS = 0
ITS_A_BUG = 1
WRONG_PASSWORD = 2
ABNORMAL_STATE = 3
NEED_CAPTCHA = 4
EXCESSIVE_WRONG_PASSWORD = 5
UNEXPECTED_ERROR = 6
WRONG_CAPTCHA = 7
